BotName: botname
Lark:
  AppID: appid
  AppSecret: appsecret
  VerifyToken: VerifyToken
  EncryptKey: ""
ChatGPT:
  Host: http://chatgpt:8000
  Token: ""
  Timeout: 3m
Message:
  ExtractFailed: "内部错误"
  UpstreamFailed: "upstream failed"
  FilterMap:
    贩毒:
    - 我不想和你谈论这个
    - 我不告诉你
