apiVersion: apps/v1
kind: Deployment
metadata:
  name: larkbot
  labels:
    app: larkbot
spec:
  selector:
    matchLabels:
      app: larkbot
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: larkbot
    spec:
      containers:
      - name: larkbot
        image: larkbot:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 400m
            memory: 400Mi
        ports:
        - containerPort: 9999
          name: http
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: larkbot
spec:
  selector:
    app: larkbot
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9999
    targetPort: 9999
